name: Build Fritzing for MacOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install Qt
        uses: jurplel/install-qt-action@v4

      - name: Run Build
        run: |
          ls -l
          qmake -spec macx-xcode
          ls -l
          
          
